{url: 'https://www.hxm5.com/s/bug%E4%BB%B7/', type: 'web', xp_t: '//li[@class="card"]/a/h2',xp_u: '//li[@class="card"]/a/@href',pre_u: '',name: '线报屋-bug价(XPath)', list: 'hmd',int: "220"},
{url: 'https://www.hxm5.com/s/bug%E4%BB%B7/', type: 'web', reg_t: '<h2>(.*?)</h2>',reg_u: 'href="([^"]*)"',pre_u: 'https://www.hxm5.com',name: '线报屋-bug价(Regex)', list: 'hmd',int: "220"},
{ url: 'https://new.xianbao.fun/plus/json/push.json', type: 'xianbao', name: '线报网-全部', list:'bmd' ,int:"100"}, 
{ url: 'https://new.xianbao.fun/plus/json/push_10.json', type: 'xianbao', name: '线报网-微博线报', list:'bmd' ,int:"120"},
{ url: 'https://new.xianbao.fun/plus/json/push_11.json', type: 'xianbao', name: '线报网-小嘀咕', list:'bmd' ,int:"140"},
{ url: 'https://new.xianbao.fun/plus/json/push_16.json', type: 'xianbao', name: '线报网-赚客吧', list:'bmd' ,int:"160"},
{ url: 'https://new.xianbao.fun/plus/json/push_18.json', type: 'xianbao', name: '线报网-新赚吧', list:'bmd' ,int:"180"},
{ url: 'https://new.xianbao.fun/plus/json/push_19.json', type: 'xianbao', name: '线报网-什么值得买', list:'bmd' ,int:"200"},
{ url: 'https://new.xianbao.fun/plus/json/push_23.json', type: 'xianbao', name: '线报网-豆瓣线报', list:'bmd' ,int:"220"},
